// <auto-generated />
using System;
using EloLab.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EloLab.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260202210346_AddArquivoUrlToTrabalho")]
    partial class AddArquivoUrlToTrabalho
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EloLab.API.Models.Anexo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome_arquivo");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("tamanho_bytes");

                    b.Property<string>("TipoArquivo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_arquivo");

                    b.Property<Guid>("TrabalhoId")
                        .HasColumnType("uuid")
                        .HasColumnName("trabalho_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("TrabalhoId");

                    b.ToTable("anexos");
                });

            modelBuilder.Entity("EloLab.API.Models.Clinica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EmailContato")
                        .HasColumnType("text")
                        .HasColumnName("email_contato");

                    b.Property<string>("Endereco")
                        .HasColumnType("text")
                        .HasColumnName("endereco");

                    b.Property<string>("Nif")
                        .HasColumnType("text")
                        .HasColumnName("nif");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Telefone")
                        .HasColumnType("text")
                        .HasColumnName("telefone");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.ToTable("clinicas");
                });

            modelBuilder.Entity("EloLab.API.Models.Laboratorio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("CorPrimaria")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cor_primaria");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EmailContato")
                        .HasColumnType("text")
                        .HasColumnName("email_contato");

                    b.Property<string>("Endereco")
                        .HasColumnType("text")
                        .HasColumnName("endereco");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text")
                        .HasColumnName("logo_url");

                    b.Property<string>("Nif")
                        .HasColumnType("text")
                        .HasColumnName("nif");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("Telefone")
                        .HasColumnType("text")
                        .HasColumnName("telefone");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.ToTable("laboratorios");
                });

            modelBuilder.Entity("EloLab.API.Models.LaboratorioClinica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ClinicaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LaboratorioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClinicaId");

                    b.HasIndex("LaboratorioId");

                    b.ToTable("LaboratorioClinicas");
                });

            modelBuilder.Entity("EloLab.API.Models.Mensagem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("NomeRemetente")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome_remetente");

                    b.Property<Guid>("RemetenteId")
                        .HasColumnType("uuid")
                        .HasColumnName("remetente_id");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("conteudo");

                    b.Property<Guid>("TrabalhoId")
                        .HasColumnType("uuid")
                        .HasColumnName("trabalho_id");

                    b.HasKey("Id");

                    b.HasIndex("TrabalhoId");

                    b.ToTable("mensagens");
                });

            modelBuilder.Entity("EloLab.API.Models.Servico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<Guid>("LaboratorioId")
                        .HasColumnType("uuid")
                        .HasColumnName("laboratorio_id");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("material");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<int>("PrazoDiasUteis")
                        .HasColumnType("integer")
                        .HasColumnName("prazo_dias_uteis");

                    b.Property<decimal>("PrecoBase")
                        .HasColumnType("numeric")
                        .HasColumnName("preco_base");

                    b.HasKey("Id");

                    b.HasIndex("LaboratorioId");

                    b.ToTable("servicos");
                });

            modelBuilder.Entity("EloLab.API.Models.Trabalho", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ArquivoUrl")
                        .HasColumnType("text")
                        .HasColumnName("arquivo_url");

                    b.Property<Guid>("ClinicaId")
                        .HasColumnType("uuid")
                        .HasColumnName("clinica_id");

                    b.Property<string>("CorDente")
                        .HasColumnType("text")
                        .HasColumnName("cor_dente");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DataEntregaPrevista")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_entrega_prevista");

                    b.Property<string>("Dentes")
                        .HasColumnType("text")
                        .HasColumnName("dentes");

                    b.Property<string>("DescricaoPersonalizada")
                        .HasColumnType("text")
                        .HasColumnName("descricao_personalizada");

                    b.Property<Guid>("LaboratorioId")
                        .HasColumnType("uuid")
                        .HasColumnName("laboratorio_id");

                    b.Property<string>("PacienteNome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("paciente_nome");

                    b.Property<Guid?>("ServicoId")
                        .HasColumnType("uuid")
                        .HasColumnName("servico_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<decimal>("ValorFinal")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_final");

                    b.HasKey("Id");

                    b.HasIndex("ClinicaId");

                    b.HasIndex("LaboratorioId");

                    b.HasIndex("ServicoId");

                    b.ToTable("trabalhos");
                });

            modelBuilder.Entity("EloLab.API.Models.Anexo", b =>
                {
                    b.HasOne("EloLab.API.Models.Trabalho", "Trabalho")
                        .WithMany()
                        .HasForeignKey("TrabalhoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trabalho");
                });

            modelBuilder.Entity("EloLab.API.Models.LaboratorioClinica", b =>
                {
                    b.HasOne("EloLab.API.Models.Clinica", "Clinica")
                        .WithMany()
                        .HasForeignKey("ClinicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EloLab.API.Models.Laboratorio", "Laboratorio")
                        .WithMany()
                        .HasForeignKey("LaboratorioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinica");

                    b.Navigation("Laboratorio");
                });

            modelBuilder.Entity("EloLab.API.Models.Mensagem", b =>
                {
                    b.HasOne("EloLab.API.Models.Trabalho", "Trabalho")
                        .WithMany()
                        .HasForeignKey("TrabalhoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trabalho");
                });

            modelBuilder.Entity("EloLab.API.Models.Servico", b =>
                {
                    b.HasOne("EloLab.API.Models.Laboratorio", "Laboratorio")
                        .WithMany()
                        .HasForeignKey("LaboratorioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Laboratorio");
                });

            modelBuilder.Entity("EloLab.API.Models.Trabalho", b =>
                {
                    b.HasOne("EloLab.API.Models.Clinica", "Clinica")
                        .WithMany()
                        .HasForeignKey("ClinicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EloLab.API.Models.Laboratorio", "Laboratorio")
                        .WithMany()
                        .HasForeignKey("LaboratorioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EloLab.API.Models.Servico", "Servico")
                        .WithMany()
                        .HasForeignKey("ServicoId");

                    b.Navigation("Clinica");

                    b.Navigation("Laboratorio");

                    b.Navigation("Servico");
                });
#pragma warning restore 612, 618
        }
    }
}
